### ISSUE TITLE
Increase compatibility with Control.Lens

### ISSUE THREAD

**Issue by andreasabel** [feuerbach/data-lens-light#8]
It would be nice to switch more easily from the `lens` package to your lightweight version.
For instance, you could add aliases to define the most basic lens applications, such as `over`, `set`, `use`.
Currently, if I want to switch, I have to create my own compatibility module.

For instance, here is a wrapper I needed for a small project:
```haskell
module Lens
  ( module Data.Lens.Light
  , module Lens
  ) where

import Data.Lens.Light

over = modL
set  = setL
use  = access
_2   = lens snd $ \ y (x, _) -> (x, y)
```

**Comment by feuerbach** [comment]
Aren't there already Control.Lens-compatible lightweight packages (lens-family, lens-family2, lens-simple etc.)?

In any case, I am not really interested in extending the functionality of this package beyond my own needs, sorry. The abundance of combinators such as `over`, `set`, `use` that I never managed to learn is what made me not want to use lens in the first place.

**Comment by andreasabel** [comment]
I see.  Well, I use your package anyway, since it is entirely self-contained.

Best, Andreas

**Comment by llelf** [comment]
@andreasabel what's wrong with microlens?

**Comment by andreasabel** [comment]
I have not considered it, but from a quick glance it still looks quite complicated for what I need.
